# yaml pipeline for .NIT.class-7.30am batch

trigger:
  none

pool:
 name: sonar
 demands :
   - agent.name -equals agentforclass

stages:
  - stage:
    displayName: maven_compile
    jobs:
      - job: maven_compile
        steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'Pay-As-You-Go(40c8e225-3409-415e-9d23-089206254341)'
              mavenPomFile: 'pom.xml'
              goals: 'compile'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
